### ISSUE TITLE
Impact decals (bullet/blast) don't show on detail brushes

### ISSUE THREAD

**Issue by GooberRF** [rafalh/dashfaction#40]
Bullet and blast decals don't show on detail brushes (or brushes that don't touch the "main" level geometry). They only show on normal brushes and moving brushes. On the PS2 version, I believe they showed on detail brushes and normal brushes, but not movers.

Decals placed in RED seem to have no issue displaying on detail brushes, though.

This is an RF bug, not specific to Dash.

**Comment by rafalh** [comment]
I don't think it should be fixed, especially not for old maps. I used to shoot brushes and find ones that don't show decals to determine which are different from others.

**Comment by GooberRF** [comment]
That's a good point, especially for some run maps. Maybe it could be a
clientside option in that case to have decals properly applied? That way if
a client wanted to use it to tell the difference between brushes they could
still have an option to do that.
